from loadDB import LoadDB

from datetime import datetime


class Main:
    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print("Current Time ImportsBegin =", current_time)
    p1 = LoadDB()
    p1.load_artist()
    p1.load_artist_credit_name()
    p1.load_artist_credit()
    p1.load_track()
    p1.load_medium()
    p1.load_recording()
    p1.load_release()
    p1.load_medium_format()
    p1.load_area()
    p1.load_gender()
    p1.load_area_type()
    p1.load_label()
    p1.load_artist_alias()
    now1 = datetime.now()
    current_time1 = now1.strftime("%H:%M:%S")
    print("Current Time RelationsBegin=", current_time1)
    p1.relate_artist_alias()
    p1.relate_artist_credit_name()
    p1.relate_artist_credit()
    p1.relate_release_ac()
    p1.relate_recording_ac()
    p1.relate_medium_release()
    now2 = datetime.now()
    current_time2 = now2.strftime("%H:%M:%S")
    print("Current Time RecTrack1=", current_time2)
    p1.relate_recording_track()
    p1.relate_medium_format()
    p1.relate_artist_area()
    p1.relate_artist_gender()
    p1.relate_area_type()
    p1.relate_medium_track()
    p1.relate_label_area()
    now3 = datetime.now()
    current_time3 = now3.strftime("%H:%M:%S")
    print("FIM Time RecTrack2=", current_time3)
    p1.relate_track_ac()
    now4 = datetime.now()
    current_time4 = now4.strftime("%H:%M:%S")
    print("Current Time =", current_time4)

    p1.close_connection()
